import 'package:flutter/material.dart';
import 'package:spotify_clone_app/models/genres.dart';

class GenreOperations {
  GenreOperations._();
  static List<Genres> getGenres() {
    return <Genres>[
      Genres(
        genre: 'Music',
        imageURL: 'assets/categories_thumbnail/TTH.jpg',
        bgcolor: const Color(0xffdc148c),
        title1: "",
        title2: "",
        listViewImgs1: [
          ['assets/categories_thumbnail/TTH.jpg']
        ],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Music',
        imageURL: 'assets/categories_thumbnail/TTH.jpg',
        bgcolor: const Color(0xffdc148c),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Music',
        imageURL: 'assets/categories_thumbnail/TTH.jpg',
        bgcolor: const Color(0xffdc148c),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Music',
        imageURL: 'assets/categories_thumbnail/TTH.jpg',
        bgcolor: const Color(0xffdc148c),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Hindi',
        imageURL: 'assets/categories_thumbnail/Hindi.jpg',
        bgcolor: const Color(0xffdc148c),
        title1: "Popular Hindi Playlists",
        title2: "",
        listViewImgs1: [
          [
            'assets/categories_thumbnail/TTH.jpg',
            'Hot Hits Hindi',
            '2,227,577 followers',
          ],
          [
            'assets/categories_thumbnail/Punjabi.jpg',
            'Hot Hits Hindi',
            '1786970 followers',
          ],
          [
            'assets/categories_thumbnail/Hindi.jpg',
            'Hot Hits Hindi',
            '1786970 followers',
          ],
          [
            'assets/categories_thumbnail/Tamil.jpg',
            'Hot Hits Hindi',
            '1786970 followers',
          ],
        ],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Punjabi',
        imageURL: 'assets/categories_thumbnail/Punjabi.jpg',
        bgcolor: const Color(0xffb02897),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Tamil',
        imageURL: 'assets/categories_thumbnail/Tamil.jpg',
        bgcolor: const Color(0xffa56752),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Charts',
        imageURL: 'assets/categories_thumbnail/Charts.jpg',
        bgcolor: const Color(0xff8c67ac),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Telugu',
        imageURL: 'assets/categories_thumbnail/Telugu.jpg',
        bgcolor: const Color(0xffb45b07),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Malayalam',
        imageURL: 'assets/categories_thumbnail/Malayalam.jpg',
        bgcolor: const Color(0xff416f86),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Summer',
        imageURL: 'assets/categories_thumbnail/Summer.jpg',
        bgcolor: const Color(0xff27856a),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Discover',
        imageURL: 'assets/categories_thumbnail/Discover.jpg',
        bgcolor: const Color(0xff8c67ac),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Party',
        imageURL: 'assets/categories_thumbnail/Party.jpg',
        bgcolor: const Color(0xff8c67ac),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Chill',
        imageURL: 'assets/categories_thumbnail/Chill.jpg',
        bgcolor: const Color(0xffb06339),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Music',
        imageURL: 'assets/categories_thumbnail/TTH.jpg',
        bgcolor: const Color(0xffdc148c),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Music',
        imageURL: 'assets/categories_thumbnail/TTH.jpg',
        bgcolor: const Color(0xffdc148c),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Music',
        imageURL: 'assets/categories_thumbnail/TTH.jpg',
        bgcolor: const Color(0xffdc148c),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
      Genres(
        genre: 'Music',
        imageURL: 'assets/categories_thumbnail/TTH.jpg',
        bgcolor: const Color(0xffdc148c),
        title1: "",
        title2: "",
        listViewImgs1: [],
        listViewImgs2: [],
      ),
    ];
  }
}
